[package]
name = "chum"
version = "0.1.0"
authors = ["Kody Kantor <kody@kkantor.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
rand = "0.6"
uuid = { version = "0.8", features = ["v4"] }
curl = "0.4"
